export interface Cliente {
  codigo_cliente_omie: number,
  razao_social: string,
  cnpj_cpf: string,
  nome_fantasia: string,
  telefone1_ddd: string,
  telefone1_numero: string,
  endereco: string,
  endereco_numero: string,
  bairro: string,
  complemento: string,
  estado: string,
  cidade: string,
  cep: string,
  email: string,
  inscricao_estadual: string,
}
